apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cm-reader
  namespace: grafana-noperator
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-reader
  namespace: grafana-noperator
subjects:
- kind: ServiceAccount
  name: default 
  namespace: grafana-noperator
roleRef:
  kind: Role 
  name: cm-reader
  apiGroup: rbac.authorization.k8s.io