apiVersion: v1
data:
  dashboards.yaml: |-
    apiVersion: 1
    providers:
      - name: 'providername'
        orgId: 1
        folder: 'Default'
        folderUid: ''
        type: file
        updateIntervalSeconds: 10
        allowUiUpdates: false
        options:
          path: /grafana-dashboard-definitions/0
          foldersFromFilesStructure: false
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: grafana-noperator
---
apiVersion: v1
data:
  datasources.yaml: ewogICAgImFwaVZlcnNpb24iOiAxLAogICAgImRhdGFzb3VyY2VzIjogWwogICAgICAgIHsKICAgICAgICAgICAgImFjY2VzcyI6ICJwcm94eSIsCiAgICAgICAgICAgICJlZGl0YWJsZSI6IGZhbHNlLAogICAgICAgICAgICAibmFtZSI6ICJwcm9tZXRoZXVzIiwKICAgICAgICAgICAgIm9yZ0lkIjogMSwKICAgICAgICAgICAgInR5cGUiOiAicHJvbWV0aGV1cyIsCiAgICAgICAgICAgICJ1cmwiOiAiaHR0cDovL3Byb21ldGhldXMtazhzLm1vbml0b3Jpbmcuc3ZjOjkwOTAiLAogICAgICAgICAgICAidmVyc2lvbiI6IDEKICAgICAgICB9CiAgICBdCn0=
kind: Secret
metadata:
  name: grafana-datasources
  namespace: grafana-noperator  
type: Opaque
---
apiVersion: v1
data:
  grafana.ini: W3NlcnZlcl0NCnJvb3RfdXJsID0gPHJvb3QgdXJsPg0KW2RhdGVfZm9ybWF0c10NCmRlZmF1bHRfdGltZXpvbmUgPSBVVEMNClthdXRoLmF6dXJlYWRdDQpuYW1lID0gQXp1cmUgQUQNCmVuYWJsZWQgPSB0cnVlDQphbGxvd19zaWduX3VwID0gdHJ1ZQ0KY2xpZW50X2lkID0gPGNsaWVudCBpZD4NCmNsaWVudF9zZWNyZXQgPSA8Y2xpZW50IHNlY3JldD4NCnNjb3BlcyA9IG9wZW5pZCBlbWFpbCBwcm9maWxlDQphdXRoX3VybCA9IDxhdXRoIHVybD4NCnRva2VuX3VybCA9IDx0b2tlbiB1cmw+DQphbGxvd2VkX2RvbWFpbnMgPQ0KYWxsb3dlZF9ncm91cHMgPSA8Z3JvdXAgdWlkPg0Kcm9sZV9hdHRyaWJ1dGVfc3RyaWN0ID0gZmFsc2UNCmFsbG93X2Fzc2lnbl9ncmFmYW5hX2FkbWluID0gZmFsc2Ug
kind: Secret
metadata:
  name: grafana-config
  namespace: grafana-noperator
type: Opaque